Setup

In [1]:
import numpy as np
import time

Section 1 — ndarray Fundamentals

Task 1.1: Array Creation & Shapes

In [2]:
# TODO:
# Create a 1D array with values 0 to 99 (no loops)

# HINT:
# - Use np.arange

arr_1d = np.arange(100)
arr_1d


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
# TODO:
# Reshape arr_1d into a (10, 10) array

# HINT:
# - reshape does NOT copy data

arr_2d = arr_1d.reshape(10, 10)
arr_2d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [4]:
# TODO:
# Create a 3D array of shape (4, 5, 3)

# HINT:
# - Total elements must match

arr_3d = np.arange(4*5*3).reshape(4, 5, 3)
arr_3d.shape
#print(arr_3d)



(4, 5, 3)

**Explain:**
- What does `.shape` represent?
- Why does contiguous memory matter?


Section 1.2 — dtype & Memory

In [5]:
# TODO:
# Create two arrays with same values but different dtypes
base = np.arange(1000)
arr_int = base.astype(np.int64)
arr_float = base.astype(np.float64)

In [6]:
# TODO:
# Compare memory usage

# HINT:
# - Use .nbytes
# 8 bytes for 1 element , so 1000 elements will take 8000 bytes
print('int bytes:', arr_int.nbytes)
print('float bytes:', arr_float.nbytes)

int bytes: 8000
float bytes: 8000


**Interview Question:**  
Why does dtype selection matter in large ML pipelines?


Section 2 — Indexing, Views & Copies

Task 2.1: Views vs Copies

Views:
In view Original array gets change
Accidentally modifying training data = BAD 
Views save memory but are dangerous if not careful

Copies:
New Memory created and safe to modify


In [7]:
# TODO:
# Create a 2D array and slice every alternate row

# HINT:
# - Use slicing, not fancy indexing

A = np.arange(20).reshape(10, 2)
A_slice = A[::2]
A_slice


array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [8]:
# TODO:
# Modify A_slice and observe A
#A_slice.shape
# When you don't want to change the original array, use fancy indexing to create a copy of the array.
# When you want changes to reflect in the original array, use slicing to create a view of the array.
A_slice[0, 0] = -999 # view, shares memory so takes less memory

A_copy = A[[0,2,4]] # selects rows 0,2,4 , but makes a copy.


A_copy[0, 0] = 125678 # copy

print('A_copy:', A_copy)
# print('A_slice:', A_slice)
print('A:', A)


A_copy: [[125678      1]
 [     4      5]
 [     8      9]]
A: [[-999    1]
 [   2    3]
 [   4    5]
 [   6    7]
 [   8    9]
 [  10   11]
 [  12   13]
 [  14   15]
 [  16   17]
 [  18   19]]


Explain:
- Why did the original array change (or not)?


Section 2.2 — Boolean Masking

In [9]:
# TODO:
# Create random array of size 1000

rng = np.random.default_rng(0)
X = rng.standard_normal(1000)



In [ ]:
# TODO:
# Extract values greater than mean

# HINT:
# - Mean first = sum of elements / number of elements
# - Boolean mask = Numpy keeps only the True values
# Use in ML : Removing Invalid data points
m = X.mean()
above_mean = X[X > m] # elements greater than mean





In [11]:
# TODO:
# Replace negative values with 0 (no loops)

X_copy = X.copy()
X_copy[X_copy < 0] = 0 # replace negative values with 0

print('mean :', m)
print('above mean count :', above_mean.size)
print('negatives after replacing :', (X_copy < 0).sum())

mean : -0.04802827676298692
above mean count : 488
negatives after replacing : 0


Section 3 — Broadcasting

Task 3.1: Broadcasting Rules

In [12]:
# TODO:
# Create A (1000, 50) and b (50,)
rng = np.random.default_rng(1)
A = rng.standard_normal((1000, 50))
b = rng.standard_normal((50,))


In [13]:
# TODO:
# Add b to each row of A

# HINT:
# - No reshape required
A_plus_b = A + b  # broadcasting


In [14]:
# TODO:
# Normalize each row of A

# HINT:
# - Axis matters
# - Keep dimensions in mind
# std deviation = sqrt( mean( (x - mean(x))**2 ) )

# row - mean(row) / std(row)

row_mean = A.mean(axis=1, keepdims=True) # aixs=1 for row-wise operation, compute mean for each row

row_std = A.std(axis=1, keepdims=True) # compute std deviation for each row

A_normalized = (A - row_mean) / row_std
A_normalized.shape






(1000, 50)

Explain broadcasting step-by-step.


Section 3.2 — Broadcasting Trap

In [15]:
# TODO:
# Intentionally trigger a broadcasting error
# Then fix it
col = np.arange(1000)  # shape (1000,)
try:
    _ = A - col
except ValueError as e:
    print('Broadcasting error:', e)

col2 = col.reshape(-1,1)

A_fixed = A - col2
A_fixed.shape


Broadcasting error: operands could not be broadcast together with shapes (1000,50) (1000,) 


(1000, 50)

What was wrong with the original shapes?


Section 4 — Vectorization vs Loops

Task 4.1: Loop vs Vectorized

In [16]:
# TODO:
# Create large array X of size 1,000,000
rng = np.random.default_rng(2) # random number generator
X = rng.standard_normal(1_000_000) # array of 1 million random numbers


In [ ]:
# TODO:
# Normalize using Python loop

# HINT: 
# - Time it
mu = X.mean() # mean
sigma = X.std() # standard deviation = how spread out the numbers are/ aaverage distance from mean
t0 = time.time() # start time
out_loop = np.empty_like(X) # output array

for i in range(X.shape[0]):
    out_loop[i] = (X[i] - mu) / sigma
time_taken = time.time() - t0
print(round(time_taken, 4))




0.1517


In [18]:
# TODO:
# Normalize using vectorization
t1 = time.time()
out_vec = (X - mu) / sigma
vec_time = time.time() - t1
round(vec_time, 4)
print(round(time_taken / max(vec_time, 1e-12), 1))
print('allclose:', np.allclose(out_loop, out_vec))



43.7
allclose: True


Why is vectorization faster?


Task 4.2: Pairwise Distance (FAANG Classic)

In [19]:
# TODO:
# Compute pairwise Euclidean distance matrix without loops

# HINT:
# - Use (x - y)^2 expansion
# - Broadcasting is key

def pairwise_distance(X):

    sq = np.sum(X * X, axis=1, keepdims=True)  # shape (n, 1)
    dist = sq + sq.T - 2 *(X @ X.T)
    dist = np.maximum(dist, 0.0)  
    return np.sqrt(dist)

rng = np.random.default_rng(3)
Xsmall = rng.standard_normal((200, 10))
D = pairwise_distance(Xsmall)
print(D.shape)  # should be (200, 200)
print('diag ~ 0 :' , np.allclose(np.diag(D), 0, atol=1e-7))  # diagonal should be ~0
print('symmetry :', np.allclose(D, D.T))  # should be symmetric
    


(200, 200)
diag ~ 0 : True
symmetry : True


Section 5 — Numerical Stability =  It refers to how sensitive a algorithm is in response to small errors.

Task 5.1: Softmax

In [20]:
# TODO:
# Implement naive softmax

def softmax_naive(X):
    ex = np.exp(X)

    return ex/ex.sum(axis=0, keepdims=True)

Xbig = np.array([[1000.0, 1001.0, 1002.0]])

try:
    softmax_naive(Xbig)
except FloatingPointError as e:
    print('Numerical issue in softmax_naive:', e)


/var/folders/2q/m52t0mh101x6yzvcxqzy0bzh0000gn/T/ipykernel_4568/2749026938.py:5: RuntimeWarning: overflow encountered in exp
  ex = np.exp(X)
/var/folders/2q/m52t0mh101x6yzvcxqzy0bzh0000gn/T/ipykernel_4568/2749026938.py:7: RuntimeWarning: invalid value encountered in divide
  return ex/ex.sum(axis=0, keepdims=True)


In [21]:
# TODO:
# Fix numerical instability

# HINT:
# - Subtract max per row

def softmax_stable(X):
    Z = X - X.max(axis=1, keepdims=True)
    print('Z:', Z)
    ex = np.exp(Z)
    return ex / ex.sum(axis=1, keepdims=True)

print('stable softmax:', softmax_stable(Xbig))
print('rowsum :', softmax_stable(Xbig).sum(axis=1))


Z: [[-2. -1.  0.]]
stable softmax: [[0.09003057 0.24472847 0.66524096]]
Z: [[-2. -1.  0.]]
rowsum : [1.]


Why does subtracting max work?


Section 6 — Linear Algebra

Task 6.1: Matrix Multiplication

In [22]:
# TODO:
# Try valid and invalid matrix multiplications
# Matrix Multiplication : It's only possible when columns of first matrix = rows of second matrix
A = np.random.default_rng(3).standard_normal((3, 4))

B = np.random.default_rng(4).standard_normal((4, 2))

mat_mul = A @ B  # valid multiplication
print( mat_mul.shape)


try:
    _ = A @ A  # invalid multiplication
except ValueError as e:
    print('Matrix multiplication error:', e)


# @, np.dot, and np.matmul are equivalent for 2D arrays, difference is @ is easier to read and write
# matmul is older version
print('A @ B ==. dot.product', np.allclose(np.dot(A, B), mat_mul)) # true
print('matmul == A @ B', np.allclose(np.matmul(A, B), mat_mul)) # true

(3, 2)
Matrix multiplication error: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)
A @ B ==. dot.product True
matmul == A @ B True


Explain difference between dot, @, and matmul.


Task 6.2: Solving Linear Systems

In [23]:
# TODO:
# Solve Ax = b and verify solution

rng = np.random.default_rng(6)
A = rng.standard_normal((5, 5)) # has 2 dimensions
b = rng.standard_normal((5,)) # only has 1 dimension
x = np.linalg.solve(A, b) 
resid = np.linalg.norm(A @ x - b) # how far Ax is from b 
print('residual norm :', resid) 


residual norm : 1.3472180148700993e-15


Section 7 — Performance & Memory

Task 7.1: In-Place Operations

In [24]:
# TODO:
# Compare in-place vs out-of-place operations

X = np.random.default_rng(7).standard_normal(2_000_000)
Y = X.copy() # when i create a copy they both (X & Y) occupy different memory locations
t0 = time.time()
Z = X + 1.0  # out-of-place = creates a new array
t_out = time.time() - t0

t1 = time.time()
Y += 1.0  # in-place 
t_in = time.time() - t1

print('out-of-place time:', round(t_out, 4))
print('in-place time:', round(t_in, 4))
# In-place is generally faster and uses less memory since it modifies the existing array rather than creating a new one.
 


out-of-place time: 0.0027
in-place time: 0.0016


Task 7.2: Strides

In [25]:
# TODO:
# Inspect array strides and explain
A = np.arange(24).reshape(6, 4)
print('shape', A.shape)
print('strides', A.strides) # Strides = It tells how many bytes we need to skip in memory to move to the next element along each dimension.

B  = A[:, ::2]  # slicing every alternate column
print('B shape', B.shape)
print('B strides', B.strides)

# Explanation:
# In a 2D array, the strides indicate how many bytes you need to skip in memory to move to the next row and the next column.
# Here, each element is of type int64, which typically takes up 8 bytes.
# EX:
# (32,8) 
#      0 1 2 3
#      4 5 6 7
# In order to move to the next row (from 0 to 4), we need to skip 4 elements * 8 bytes/element = 32 bytes.
# In order to move to the next column (from 0 to 1), we need to skip 1 element * 8 bytes/element = 8 bytes.

shape (6, 4)
strides (32, 8)
B shape (6, 2)
B strides (32, 16)


Section 8 — Mini Case Study

In [26]:
# TODO:
# Given X (10000, 100):
# - Normalize features
# - Compute covariance
# - Extract top-k eigenvectors

rng = np.random.default_rng(8)
X = rng.standard_normal((10_000, 100))

# Normalize features
mu = X.mean(axis=0, keepdims=True) # mean for each feature , 1 mean per column 
sigma = X.std(axis=0, keepdims=True) # standard deviation for each feature, column-wise standard deviation
Xn = (X - mu) / sigma # normalized features

# Compute covariance
C = (Xn.T @ Xn) / (Xn.shape[0] - 1)  # shape (100, 100)

# Extract top-k eigenvectors 
# Eigen - means how much is the difference in variance along that direction
eigenvalues, eigenvectors = np.linalg.eigh(C)
k = 5  # number of top eigenvectors to extract
top_idx = np.argsort(eigenvalues)[-k:][::-1] # indices of top-k eigenvalues
top_eigenvectors = eigenvectors[:, top_idx]  # shape (100, k)   
print('Top-k eigenvectors shape:', top_eigenvectors.shape)




Top-k eigenvectors shape: (100, 5)


Explain each step and its ML relevance.


1. Where did NumPy save memory?
2. Where did it avoid Python overhead?
3. Which operation would break at scale?
